org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Template Properties
mod_id=sword_blocking_key
mod_name=Sword Blocking Key
mod_class=SwordBlockingKey

# Mod Properties
mod_license=MIT
mod_version=0.1.1-1.20.1
mod_group_id=github.jodevnull
mod_authors=jo-devnull
mod_description=Adds a keybind for the Sword Block Mechanics mod

# Minecraft
mapping_channel=official
mapping_version=1.20.1
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)

# Forge
forge_version=47.4.20
forge_version_range=[47,)
loader_version_range=[47,)

# Dependencies
modrinth.sword-blocking-mechanics=v8.0.2-1.20.1-Forge
modrinth.puzzles-lib=v8.1.33-1.20.1-Forge

modrinth.emi=1.1.22+1.20.1+forge @runtimeOnly
modrinth.cloth-config=11.1.136+forge @runtimeOnly
modrinth.playeranimator=1.0.2-rc1+1.20-forge @runtimeOnly
modrinth.better-combat=1.9.0+1.20.1-forge @runtimeOnly
modrinth.architectury-api=9.2.14+forge @runtimeOnly
modrinth.simply-swords=1.56.0-1.20.1 @runtimeOnly
modrinth.simplymore=xevLkumX @runtimeOnly
