org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Template Properties
mod_id=sword_blocking_key
mod_name=Sword Blocking Key
mod_class=SwordBlockingKey

# Mod Properties
mod_license=MIT
mod_version=0.1.1-1.21.1
mod_group_id=github.jodevnull
mod_authors=jo-devnull
mod_description=Adds a keybind for the Sword Block Mechanics mod

# Minecraft
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)

# NeoForge
neo_version=21.1.227
neo_version_range=[21,)
loader_version_range=[4,)

# Dependencies
modrinth.sword-blocking-mechanics=v21.1.1-1.21.1-NeoForge
modrinth.puzzles-lib=v21.1.39-1.21.1-NeoForge

modrinth.emi=1.1.23+1.21.1+neoforge @runtimeOnly
modrinth.cloth-config=15.0.140+neoforge @runtimeOnly
modrinth.playeranimator=2.0.4+1.21.1-forge @runtimeOnly
modrinth.better-combat=2.3.2+1.21.1-neoforge @runtimeOnly
modrinth.architectury-api=13.0.8+neoforge @runtimeOnly
modrinth.simply-swords=1.63.0-1.21.1 @runtimeOnly
modrinth.simplymore=1.2.2 @runtimeOnly @runtimeOnly
modrinth.fzzy-config=0.7.6+1.21+neoforge @runtimeOnly
modrinth.simply-tooltips=0.1.3 @runtimeOnly
modrinth.kotlin-for-forge=5.11.0 @runtimeOnly